projects:
  app:
    schemaPath: server/src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: server/src/generated/prisma.graphql
    includes: ["**/*.graphql"]
    extensions:
      prisma: server/database/prisma.yml
      codegen:
      - generator: graphql-binding
        language: typescript
        output:
          binding: src/generated/db.ts
